### ISSUE TITLE
Links have extra `"` at the end

### ISSUE THREAD

**Issue by richardtallent** [vue-a11y/eslint-plugin-vuejs-accessibility#106]
Hi,

I'm glad this is out there! I'm starting a new project that requires a strong focus on a11y, and this seems like a great way to ensure we don't create a bunch of technical debt we would have to fix later.

I'm starting to test is now, and ran into a small issue. To reproduce, just put `<img />` somewhere. The error for missing alt tags comes up, but if you click on it, it goes to this URL, which has an encoded `"` character at the end:

`https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/blob/master/docs/alt-text.md%22`

This could be a VS Code issue, but if so, I haven't seen it so far with other ESLint plugins.

**Comment by kddeisz** [comment]
Oh man nice catch! Yes this is totally a bug, I'll get this fixed.

**Comment by joshuar500** [comment]
just wanted to say thank you for this library :) accessibility is so important!
