### ISSUE TITLE
Support ESLint v9

### ISSUE THREAD

**Issue by xsjcTony** [vue-a11y/eslint-plugin-vuejs-accessibility#1083]
https://eslint.org/blog/2024/04/eslint-v9.0.0-released/
It may contain some breaking changes for plugins. And peer dependency definitely need to be updated.

**Comment by kazupon** [comment]
I've been working at https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/pull/1073/

**Comment by vhoyer** [comment]
release on `2.3.0`
