### ISSUE TITLE
iframe-has-title doesn't work

### ISSUE THREAD

**Issue by snowbabykang** [vue-a11y/eslint-plugin-vuejs-accessibility#130]
I set alt-text and iframe-has-title, alt-text works, iframe-has-title doesn't work
![image](https://user-images.githubusercontent.com/12569179/114692743-78385d80-9d4b-11eb-8d35-adca24d3c0b2.png)

**Comment by MariuszDabrowski** [comment]
+1, enabling the rule and adding an iframe to the page without a title doesn't throw an error.
