### ISSUE TITLE
Rule Proposal："<strong>" and "<em>" tags should be used

### ISSUE THREAD

**Issue by snowbabykang** [vue-a11y/eslint-plugin-vuejs-accessibility#131]
I want to add aria-hidden to the \<i>； or replace \<i> with \<em>；And replace \<b> with \<strong>

Additional context

Our company uses Sonar to monitor code quality，sonar always tells us the following
![image](https://user-images.githubusercontent.com/12569179/114820672-f0f1f500-9df1-11eb-929f-823936ff52f7.png)

**Comment by mauryapari** [comment]
As per the Sonar Documentation, this rule mentioned above is now deprecated. Sonar also have not referenced any other rule to be used in place of this. Therfore, maybe we can close this issue for now.

![Sonar-html-deprecated-rule](https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/assets/47924620/ab958c65-fa13-43ea-bb96-669bf7b282af)
