### ISSUE TITLE
[Bug] context.parserServices.defineTemplateBodyVisitor is not a function

### ISSUE THREAD

**Issue by harrytran998** [vue-a11y/eslint-plugin-vuejs-accessibility#135]
When I init newest my project with the detail 
```js
root: true,
  parserOptions: {
    parser: '@typescript-eslint/parser',
    ecmaFeatures: {
      jsx: true,
      modules: true,
    },
    ecmaVersion: 2021,
    sourceType: 'module',
  },
  parser: '@typescript-eslint/parser',
  env: {
    node: true,
    browser: true,
    es6: true,
    jest: true,
  },
  globals: {
    Promise: true,
    process: true,
    console: true,
    Set: true,
    Intl: true,
  },
  plugins: [
    '@typescript-eslint',
    'vuejs-accessibility',
  ],
  extends: [
    'eslint-config-airbnb-base',
    'plugin:@typescript-eslint/recommended',
    'plugin:vuejs-accessibility/recommended',
  ],
```

Here is the package.json
```json
    "@typescript-eslint/eslint-plugin": "4.22.1",
    "@typescript-eslint/parser": "4.22.1",
    "eslint": "^7.26.0",
    "eslint-config-airbnb-base": "14.2.1",
    "eslint-plugin-vuejs-accessibility": "0.6.1",
```

I see the error ⬇️. Hope you can take a look! Maybe you need to upgrade deps 🤔.

```
TypeError: Error while loading rule 'vuejs-accessibility/accessible-emoji': context.parserServices.defineTemplateBodyVisitor is not a function
```

**Comment by harrytran998** [comment]
Sorry, my bad! It needs to install `eslint-plugin-vue` first! Hope you guy can add this line to guide people avoid this mistake like me!

**Comment by kddeisz** [comment]
That function comes from `vue-eslint-parser` (https://www.npmjs.com/package/vue-eslint-parser), which is a dependency of this package. If you install the eslint vue plugin you'll get that dependency as well, but you should have gotten it from this package. Do you see it in your `package-lock.json`/`yarn.lock`?

**Comment by harrytran998** [comment]
I don't have `vue-eslint-parser` in my packages.json! So you mean which I do not need to have `eslint-plugin-vue`, just need `vue-eslint-parser` then this packages will work?

**Comment by kddeisz** [comment]
No I'm saying when you install all of the dependencies, `npm` or `yarn` will see that `vue-eslint-parser` is a dependency of this package and will pick it up. It shouldn't be in your `package.json` it should be in your package lock.

**Comment by harrytran998** [comment]
Thank you for your work!
