### ISSUE TITLE
form-control-has-label does not check children of siblings

### ISSUE THREAD

**Issue by jashaj** [vue-a11y/eslint-plugin-vuejs-accessibility#924]
I have a checkbox with a label and extra description. To align the description with the `label`, I have wrapped them in a `div`:

```html
<div class="checkbox">
  <input id="myCheckbox" type="checkbox" aria-describedby="myCheckboxInfo" />
  <div class="checkbox-label">
    <label for="myCheckbox">I agree</label>
    <p id="myCheckboxInfo">Here is some extra info what I agree upon</p>
  </div>
</div>
```

The plugin sees this as a violation of `form-control-has-label` even though there is a `label/@for` that refers to the `id` of the checkbox. The `function hasLabelElement` only checks the children of the parent but not their children.

**Comment by vhoyer** [comment]
what do you think? https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility/pull/975

**Comment by jashaj** [comment]
Thank you :-)
